# UTS-3 My Stories for You

> Stories are made to be remembered, not to be forgotten.

## Proses Mencari Jati Diri
***"Siapakah diri saya?"***  
Sebuah perjalanan dalam mengenal diri saya yang sebenarnya. Awal hidup saya yang biasa-biasa saja, banyaknya kesalahan yang saya lakukan dan alami berdampak pada perspektif 
terhadap diri saya yang sebenarnya.  
  
Berawal ketika saya mengalami kesulitan dalam mengenali diri dan apa yang saya inginkan untuk menjadi kedepannya. Namun, walaupun sampai sekarang
saya masih belum menemukan jawabannya. Hidup saya berputar pada sebuah pertanyaan bukan jawaban. Semakin saya mencari tahu jawabannya, semakin banyak pertanyaan yang saya miliki.  
  
Akhir Desember tahun 2024 saya mulai untuk mencari hobi dan kesenangan lainnya, saya memulai untuk mempelejari design dan UI/UX lalu mendapatkan landing intern saya pertama di BAWASLU.
Menjelang masa magang saya merasa bahwa ketertarikan saya dengan teknologi semakin kuat. Lalu sampai sekarang, saya masih mencari jawaban apa gunanya saya lahir di dunia ini? apa tuuan dan manfaat saya
yang saya bisa tinggalkan di dunia ini selain ibadah? pertanyaan inilah yang akan terus saya tanyakan.

> Pesan yang diambil: "Mencari jati diri sendiri sama seperti mencari emas di gunung"

## Bekas Luka Tanganku
***Fun fact: aku memiliki bekas luka sobek di tangan kananku***    
Sejak saya berusia 2 tahun saya sudah memiliki bekas luka yang mendalam di tangan kanan saya. Saya pun tidak ingat kejadiannya, namun saya seringkali mendapatkan cerita dari mana bekas luka tangan tersebut berasal.  
  
Berawal ketika saya masih sangat lincah sebagai anak kecil. Yap, cukup lincah, tidak bisa diam, tapi tidak nakal ;D.  
Soal nakal... mungkin tindakan saya yang ini bisa dibilang sebaliknya. Saat itu, saya sedang berlari
-larian, sesaat tepat di dapur saya tidak sengaja menabrak bibi saya saat mencuci piring.   
Tak disangka kejadiannya terjadi ketika bibi saya sedang memegang piring di tangannya dan nasib buruknya
piring tersebut merupakan piring kaca. Piring itu pun jatuh dan menimpa tepat dekat urat nadi di tangan kanan saya.  
  
Semua orang rumah, saat itu panik dan langsung mengantarkan saya ke rumah sakit.
Tak ada opsi lain, saya pun harus dioperasi dan memastikan pendarahan saya agar tidak menyebabkan saya kehilangan banyak darah. Dan dari situlah terbit bekas luka yang sudah hampir 21 tahun saya miliki di tangan kanan saya,
kini kami berteman dan saya seringkali tidak lupa dan mengkaitkan bekas luka tersebut sebagai memori berkesan waktu saya kecil.
  
> Pesan yang diambil: "Tanggapilah kecelakaan sebagai sebuah cerita, bukan penyesalan"

## Selalu Erat dengan Musik
***Fun fact: saya memiliki 3 lagu yang fully di produced dan telah dipublished***  
COVID-19 adalah penyebab saya menjadi suka dengan musik. Musik adalah bahasa perasaan alam-semesta dan karya manusia yang paling saya kagumi. Sejak SMA dan berkat COVID-19 saya menjadi tertarik dan mulai
mendalami composing dan producing. Hanya sebatas laptop kecil dan sebuah midi piano di kamar kecil saya, saya tidak pernah berhenti untuk membuat musik.
Sampai sekarang pun saya masih memiliki niat dan keinginan untuk membuat musik.  
  
> Pesan yang diambil: "Carilah kesenangan dan kembali kepadanya"
