# UTS-2 My Songs for You

## Up and Downs
**Fix You**    
by ***Coldplay***   

<iframe data-testid="embed-iframe" 
    style="border-radius:12px" 
    src="https://open.spotify.com/embed/track/7LVHVU3tWfcxj5aiPFEW4Q?utm_source=generator" 
    width="100%" 
    height="352" 
    frameBorder="0" 
    allowfullscreen="" 
    allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
    loading="lazy"
>
</iframe>

When you try your best, but you don't succeed  
When you get what you want, but not what you need  
When you feel so tired, but you can't sleep  
Stuck in reverse  
  
And the tears come streaming down your face  
When you lose something you can't replace  
When you love someone, but it goes to waste  
Could it be worse?  
  
Lights will guide you home
And ignite your bones
And I will try to fix you
  
[...]  
  
And high up above or down below  
When you're too in love to let it go  
But if you never try, you'll never know  
Just what you're worth  
  
Lights will guide you home  
And ignite your bones  
And I will try to fix you  
  
[...]
  
Tears stream down your face  
When you lose something you cannot replace  
Tears stream down your face, and I  
  
Tears stream down your face  
I promise you I will learn from my mistakes  
Tears stream down your face, and I  
  
Lights will guide you home  
And ignite your bones  
And I will try to fix you  
  
## Artistik
**Novacane**
by ***Frank Ocean***   
  
<iframe style="border-radius:12px"
  src="https://open.spotify.com/embed/track/4osgfFTICMkcGbbigdsa53"
  width="100%" 
  height="352" 
  frameborder="0" 
  loading="lazy"
  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture">
</iframe>

I think I started somethin'  
I got what I wanted  
Did-didn't, I can't feel nothin', superhuman  
Even when I'm f*ckin', Viagra poppin'  
Every single record, autotunin'  
Zero emotion, muted emotion  
Pitch-corrected, computed emotion, uh-huh  
  
I blame it on the model broad with the Hollywood smile, aw  
Stripper booty and a rack like wow  
Brain like Berkeley, met her at Coachella  
I went to see Jigga, she went to see Z Trip  
..
Perfect  
  
I took a seat on the ice-cold lawn  
She handed me an ice blue bong, whatever  
She said she wanna be a dentist really badly  
She's in school paying for tuition doing p*rn in the Valley  
At least you working, but girl, I can't feel my face  
What are we smokin' anyway?  
She said, "Don't let the high go to waste"  
But can you taste a little taste of  
  
Novacane, baby, baby  
Novacane, baby, I want you  
f*ck me good, f*ck me long, f*ck me numb  
Love me now, when I'm gone love me none  
Love me none, love me none  
Numb, numb, numb, numb  
  
Sink full of dishes, pacing in the kitchen  
Cocaine for breakfast, yikes  
Bed full of women  
Flip on a tripod, little red light on  
Shooting, I'm feeling like Stanley Kubrick  
This is some visionary shit  
Been tryna film pleasure with my eyes wide shut, but it keeps on moving  
  
I blame it on the model broad with the Hollywood smile  
Stripper booty with a rack like wow  
I'll never forget you  
You put me on a feeling I never had, never had, never had (never)  
And ever since I've been tryna get it back  
You pick it up and put it back  
Now I'm something like the chemist on campus  
But there's no drug around  
Quite like what I found in you, you  
I still can't feel my face (oh-oh)  
What am I smokin' anyway? (Ah)  
She said, "Don't let the high go to waste" (oh-oh)  
But can you taste a little taste of?  
  
Novacane, baby, baby (oh)  
Novacane, baby, I want you  
F*ck me good, f*ck me long, f*ck me numb  
Love me now, when I'm gone, love me none  
Love me none, love me none  
Numb, numb, numb, numb  
Novacane, Novacane, Novacane, Novacane, Novacane (oh, oh, oh)  
Numb the pain, numb the pain, numb the pain  
Numb the pain, numb the pain (yeah)  
Novacane, Novacane, Novacane, Novacane, Novacane (oh, ho)  
For the pain, for the pain (ooh, huh)  
Novacane, Novacane  
  
Oh-huh, oh-huh, ho-huh  
Oh-huh, oh-ho, ho-ho-huh  
Oh-huh, oh-huh, ho-huh  
Oh-huh, oh-ho, ho-ho-huh  
  
Pretty girls involved with me  
Makin' pretty love to me, pretty, pity, pity  
All the pretty girls involved with me  
Makin' pretty love to me, pretty, pity, pity  
I can't feel a thing  
I can't feel, can't feel a thing  
Can't feel a thing, can't feel, feel, feel, feel her  
I can't feel, feel her  
Novacane, Novacane, Novacane  
I can't feel, feel her  
Novacane for the pain, for the pain  
I can't, can't feel, feel her, feel her, oh  
Novacane, Novacane, cane, cane, cane  
  
## Takes on the song
Lagu pertama **Fix You**, feelingnya mellow, haru, sedih, dan harapan. Lagu ini merepresentasikan bagaimana dunia yang kadang kejam membawakan banyaknya kesedihan dibandingkan kebahagiaan, namun dibalik itu
lagu ini merepresentasikan kepercayaan akan apa yang sudah dilalui bukanlah hal yang sia-sia, melainkan sebuah langkah untuk memperbaiki keadaan dan menjadi yang lebih baik. Lagu ini juga membuktikan
bahwa sesimpel dan sesederhana ritme, chord, struktur sebuah lagu dapat memberikan dampak yang luar biasa terhadap psikologis seseorang. Sama halnya dengan hidup yang cenderung bervariasi dan terdiri dari
kejutan akan ups and downs, tekanan yang dihadapi merupakan sebuah chorus dari lagu ini yakni sebuah momen berulang yang selalu kita rasakan namun tidak bisa dihindari. Namun dengan chorus ini, mereka memiliki tujuan
yakni tujuan sebagai sebuah jembatan menuju sebuah reff atau drop yang akan membuat kita sadar bahwa inilah momennya, inilah saatnya, dan sebuah kemenangan baik itu berupa harapan atau kejelasan akan jawaban, inilah indahnya
lagu ini.  
  
Sedangkan, **Novacane** terdengar jauh berbeda dan memiliki tempo yang lebih cepat. Lagu ini merepresentasikan bagaimana seseorang yang memiliki daya atau kemampuan kreatif akan menguasai dunia. Apapun bentuknya
sesuatu yang sifatnya simpel seperti instrument dari lagu ini yang hanya bersifat repetitif 1/1 dan bass yang cukup simpel membuktikan bahwa dunia tidak butuh hal yang bersifat kompleks untuk membuktikan sesuatu, melainkan
daya kreatiflah yang akan menunjukkan jalan yang tidak terduga. Sama layaknya lagu ini yang menjadi fokusnya adalah lyricnya yang sangat terformat dengan baik dan rapih. Uniknya lagi, lagu ini hanya menceritakan sebuah kejadian
dari artis tersebut yang terjadi di suatu hari dan suatu saat yang mungkin bisa dibilang hanya terjadi 1-2 jam saja, namun dikemas dengan lagu berdurasi 5 menit 2 detik dan akan diingat selamanya.