# UTS-1 All About Me

## Whats about me?
Ketika saya menawarkan tentang diri saya, saya hanya berpikir mungkin orang lain ingin mengenal diri saya dari sisi kepribadian seperti MBTI, keunikan, maupun sebuah wawasan yang kita dapat bagi ke seluruh dunia dan membuat diri kita merasa lebih baik.
Oke, mungkin dari keunikan saya terlebih dahulu lalu ke MBTI.

### My uniqueness
1. **Saya handal dalam "berimprovisasi":** Maksud dari "improvisasi" di sini adalah kemampuan saya dalam "meniru" seseorang. Tak jarang saya memiliki banyak panutan dalam hidup, dimulai dari orang yang saya looked up to hingga orang yang memang saya inginkan untuk menjadi seperti. 
Salah satu learning curve saya untuk menjadi pribadi yang lebih baik adalah belajar dari bagaimana seseorang yang sudah sukses di bidangnya dalam berperilaku, berbicara, dan berpikir. Sepanjang saya hidup saya merasa saya cenderung bersifat
adaptif terhadap karakter saya. Maka dari ini saya kira, saya dapat fit in sesuai dengan lingkungan yang kadang 180 derajat berbeda dari lingkungan yang saya biasanya tinggali.

2. **Saya cenderung mendalami perasaan seseorang:** Mungkin ini termasuk sifat empatetik, namun diri saya kadang berpikir dan merasa dalam ketika saya ingin memahami seseorang. Dan ini tidak hanya terjadi di waktu tertentu saja, melainkan dari segala
percakapan, interaksi, atau dampak dan sifat saya terhadap seseorang, saya cenderung memahami lebih terhadap seseorang dibandingkan memahami diri saya lebih lanjut. Mungkin borderlinenya adalah perilaku ini dekat dengan sifat judgemental atau perilaku menghakimi seseorang.
Namun, tentunya tindakan tersebut tidak akan berdampak buruk lebih lanjut kecuali saya mengutarakan apa isi pikiran saya, saya merasa ada benefitnya juga dari sifat seperti ini yakni memiliki sifat empati mendalam dan cenderung menjaga perasaan seseorang.

3. **Saya lebih suka tepat sasaran:** Dahulu saya kira belajar 12-14 jam akan berpengaruh pada sisi perspektif dan adaptabilitas otak saya, walaupun benar tetapi perspektif saya berubah semenjak kuliah. Waktu menentukan segalanya tetapi memanfaatkan waktu sebaik dan seefektif mungkin
adalah jawabannya. Kepribadian saya adalah selalu melihat sesuatu untuk cepat selesai dan memiliki output yang tepat sasaran tidak berlebihan maupun tidak kurang. Walaupun banyak sekali yang harus saya pelajari di hidup ini, bagaimana mungkin saya pelajari semuanya? saya lebih merasa cocok
apabila saya mempelajari jalan yang sesuai dengan diri saya.

### MBTI
> INFJ
Saya memiliki pribadi yang introvert yakni cenderung lelah jika terlalu banyak berinteraksi dengan orang lain dalam waktu sehari. Saya memiliki intuisi dan juga terkadang lebih mengandalkan ke perasaan dibandingkan berpikir logis. Dibalik itu kepribadian saya yang saya jelaskan sebelumnya membuat saya
memiliki kepribadian yang cukup judgemental.
